version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
      - "5555:5555"
    environment:
      DATABASE_URL: "mysql://user:password@db:3306/mydb"
      SHADOW_DATABASE_URL: "mysql://root:password@db:3306/shadowdb"
      PORT: 4000
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password

volumes:
  dbdata:
